yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: node-modules
cacheFolder: .yarn/cache
npmRegistryServer: https://registry.yarnpkg.com
defaultLanguageName: node
enableTelemetry: false
httpRetry: 10
httpTimeout: 200000000
